disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "まとめサイト"

[params]
displayName = "JA"
isoCode = "ja"
rtl = false
dateFormat = "2 January 2006"
logo = "logo.PNG"
description = ""

[[params.author.links]]
misskey = "https://misskey.io/@eimmm8"

[[params.author.links]]
twitter = "https://x.com/eimmm8"

[[params.author.links]]
blog = "https://blog.subaseka.net/"

[[params.author.links]]
wavebox = "https://wavebox.me/wave/60qinvl8w8hho3dq/"

[[params.author.links]]
link = "https://linktr.ee/eimmm8"

["params.author"]
name = "えいむ"
image = "profile.jpg"
bio = "Mail：subaseka1231★gmail.com"
headline = "インターネット地縛霊"
