disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "まとめサイト"

[params]
displayName = "JA"
isoCode = "ja"
rtl = false
dateFormat = "2 January 2006"

[[params.author.links]]
twitter = "https://x.com/eimmm8"


["params.author"]
name = "えいむ"
image = "profile.jpg"
headline = "インターネット地縛霊"
